# Generated by Django 3.0.2 on 2020-01-22 03:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VS1H1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Log_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Stakeholder_Name', models.CharField(max_length=100)),
                ('Wake_up_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Caffiene_Intake', models.CharField(max_length=100)),
                ('Exercise_Description', models.CharField(max_length=200)),
                ('Routine_Description', models.CharField(max_length=1000)),
                ('Review_Intentions', models.CharField(max_length=300)),
                ('Intended_Methods', models.CharField(max_length=1000)),
                ('Session_Duration', models.DateTimeField(max_length=1000)),
                ('Integrate_Awakening', models.CharField(max_length=1000)),
            ],
        ),
    ]
